# Domain :- Public Safety Analytics
Traffic accident database consists of all accidents that happened in Slovenia’s capital city Ljubljana between the years 1995 and 2005.

In [4]:
import mysql.connector
import pandas as pd

# =========================
# MYSQL CONNECTION
# =========================

conn = mysql.connector.connect(
    host = "localhost",
    user = "root"      ,
    password = "parth004",
    database = "Accidents"
)

# =========================
# LOAD TABLES INTO DATAFRAMES
# =========================

# Accident Data
nesreca_df = pd.read_sql("SELECT * FROM nesreca", conn)

# Person Data
oseba_df = pd.read_sql("SELECT * FROM oseba", conn)

# Administrative Unit Data
upravna_enota_df = pd.read_sql("SELECT * FROM upravna_enota", conn)

# =========================
# CHECK DATA
# =========================

print("Nesreca Table")
print(nesreca_df.head())

print("\nOseba Table")
print(oseba_df.head())

print("\nUpravna Enota Table")
print(upravna_enota_df.head())

# =========================
# CLOSE CONNECTION
# =========================

conn.close()

C:\Users\lenovo\AppData\Local\Temp\ipykernel_15724\4208125270.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  nesreca_df = pd.read_sql("SELECT * FROM nesreca", conn)
C:\Users\lenovo\AppData\Local\Temp\ipykernel_15724\4208125270.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  oseba_df = pd.read_sql("SELECT * FROM oseba", conn)

Nesreca Table
  id_nesreca klas_nesreca upravna_enota         cas_nesreca naselje_ali_izven  \
0     036738            H          5564 1995-01-01 15:30:00                 D
1     036744            B          5511 1995-01-02 12:45:00                 N
2     036755            L          5564 1995-01-01 06:00:00                 N
3     036756            B          5511 1995-01-02 20:10:00                 D
4     036764            B          5524 1995-01-03 00:15:00                 D

  kategorija_cesta oznaka_cesta_ali_naselje    tekst_cesta_ali_naselje  \
0                V                    64043                    PERNICA
1                L                    93117  IDRIJA-KOČEVŠE-KODER-VOJS
2                M                    00003   MEJA A-VIČ-ORMOŽ-MEJA RH
3                M                    010-0       MEJA I-ROBIČ - KALCE
4                N                    25001                  LJUBLJANA

  oznaka_odsek_ali_ulica   tekst_odsek_ali_ulica  ... vzrok_nesreca  \
0                  00000                 NI ULIC  ...            PR
1                  00000              NI ODSEKOV  ...            HI
2                  00246  MARIBOR(TEZNO)-HAJDINA  ...            SV
3                  01034       SP.IDRIJA-GODOVIČ  ...            SV
4                  28067         JADRANSKA ULICA  ...            PD

  tip_nesreca vreme_nesreca stanje_promet stanje_vozisce  \
0          BT             O             R             MO
1          BT             J             N             MO
2          ÈT             O             R             MO
3          ÈT             J             N             PN
4          ÈT             O             R             SP

  stanje_povrsina_vozisce         x         y    x_wgs84    y_wgs84
0                       A  556102.0  159758.0  15.727149  46.579510
1                       A  423380.0   95390.0  14.006034  45.998372
2                       A  555372.0  150260.0  15.716500  46.494126
3                       A  425085.0   96093.0  14.027932  46.004886
4                       A  460758.0  100064.0  14.488174  46.043603

[5 rows x 22 columns]

Oseba Table
  id_nesreca povzrocitelj_ali_udelezenec  starost spol upravna_enota  \
0     036738                           D     38.0    1          5507
1     036738                           D     28.0    1          5599
2     036738                           N     12.0    2          5507
3     036744                           D     24.0    1          5511
4     036744                           N     27.0    1          5524

  drzavljanstvo poskodba vrsta_udelezenca varnostni_pas_ali_celada  \
0           005        L               TV                        N
1           211        P               OA                        N
2           005        H               PT                        0
3           005        B               OA                        D
4           005        B               OA                        D

   vozniski_staz_LL  vozniski_staz_MM  alkotest  strokovni_pregled starost_d  \
0               6.0               NaN      0.11               0.08         D
1              10.0               NaN      0.00               0.00         C
2               0.0               NaN       NaN                NaN         B
3               6.0               NaN       NaN                NaN         C
4               6.0               NaN       NaN                NaN         C

  vozniski_staz_d alkotest_d strokovni_pregled_d
0               B          B                   B
1               B          A                   A
2               A          N                   N
3               B          N                   N
4               B          N                   N

Upravna Enota Table
  id_upravna_enota ime_upravna_enota  st_prebivalcev  povrsina
0             5501        Ajdovščina           23507       353
1             5502           Brežice           23253       268
2             5503             Celje           62049       230
3             5504          Cerknica           16155       483
4             5505          Črnomelj           18290       486

C:\Users\lenovo\AppData\Local\Temp\ipykernel_15724\4208125270.py:26: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  upravna_enota_df = pd.read_sql("SELECT * FROM upravna_enota", conn)

In [5]:
oseba_df

,id_nesreca,povzrocitelj_ali_udelezenec,starost,spol,upravna_enota,drzavljanstvo,poskodba,vrsta_udelezenca,varnostni_pas_ali_celada,vozniski_staz_LL,vozniski_staz_MM,alkotest,strokovni_pregled,starost_d,vozniski_staz_d,alkotest_d,strokovni_pregled_d
0,036738,D,38.0,1,5507,005,L,TV,N,6.0,NaN,0.11,0.08,D,B,B,B
1,036738,D,28.0,1,5599,211,P,OA,N,10.0,NaN,0.00,0.00,C,B,A,A
2,036738,N,12.0,2,5507,005,H,PT,0,0.0,NaN,NaN,NaN,B,A,N,N
3,036744,D,24.0,1,5511,005,B,OA,D,6.0,NaN,NaN,NaN,C,B,N,N
4,036744,N,27.0,1,5524,005,B,OA,D,6.0,NaN,NaN,NaN,C,B,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
954031,549803,N,18.0,2,5501,005,B,OA,1,NaN,NaN,0.00,0.00,B,N,A,A
954032,549804,D,27.0,1,5513,005,B,OA,1,8.0,9.0,0.00,0.00,C,B,A,A
954033,549804,N,25.0,1,5513,005,B,OA,1,6.0,10.0,0.00,0.00,C,B,A,A
954034,549805,D,41.0,1,5540,005,B,OA,1,4.0,1.0,0.96,0.00,E,A,C,A
954035,549805,N,24.0,1,5513,005,B,OA,1,0.0,10.0,0.00,0.00,C,A,A,A

In [6]:
nesreca_df

,id_nesreca,klas_nesreca,upravna_enota,cas_nesreca,naselje_ali_izven,kategorija_cesta,oznaka_cesta_ali_naselje,tekst_cesta_ali_naselje,oznaka_odsek_ali_ulica,tekst_odsek_ali_ulica,...,vzrok_nesreca,tip_nesreca,vreme_nesreca,stanje_promet,stanje_vozisce,stanje_povrsina_vozisce,x,y,x_wgs84,y_wgs84
0,036738,H,5564,1995-01-01 15:30:00,D,V,64043,PERNICA,00000,NI ULIC,...,PR,BT,O,R,MO,A,556102.0,159758.0,15.727149,46.579510
1,036744,B,5511,1995-01-02 12:45:00,N,L,93117,IDRIJA-KOČEVŠE-KODER-VOJS,00000,NI ODSEKOV,...,HI,BT,J,N,MO,A,423380.0,95390.0,14.006034,45.998372
2,036755,L,5564,1995-01-01 06:00:00,N,M,00003,MEJA A-VIČ-ORMOŽ-MEJA RH,00246,MARIBOR(TEZNO)-HAJDINA,...,SV,ÈT,O,R,MO,A,555372.0,150260.0,15.716500,46.494126
3,036756,B,5511,1995-01-02 20:10:00,D,M,010-0,MEJA I-ROBIČ - KALCE,01034,SP.IDRIJA-GODOVIČ,...,SV,ÈT,J,N,PN,A,425085.0,96093.0,14.027932,46.004886
4,036764,B,5524,1995-01-03 00:15:00,D,N,25001,LJUBLJANA,28067,JADRANSKA ULICA,...,PD,ÈT,O,R,SP,A,460758.0,100064.0,14.488174,46.043603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508988,549800,B,5513,2006-12-19 22:00:00,D,N,13004,IZOLA,00036,PITTONIJEVA ULICA,...,SV,TV,J,R,SU,A,395782.0,44457.0,13.660836,45.536552
508989,549802,B,5517,2006-12-20 14:00:00,D,L,93750,177112 IZOLA-BOLN. IZOLA,93750,NI ODSEKOV,...,PD,BT,J,N,SU,A,399890.0,44778.0,13.713355,45.540044
508990,549803,B,5513,2006-12-04 13:00:00,D,N,13004,IZOLA,00095,POLJE,...,VR,NT,O,N,MO,A,397155.0,44707.0,13.678358,45.539006
508991,549804,B,5513,2006-12-21 20:00:00,D,N,13004,IZOLA,00005,CANKARJEV DREVORED,...,OS,NT,O,N,SU,A,395841.0,44524.0,13.661577,45.537164
508992,549805,B,5513,2006-12-29 19:00:00,N,2,00111,KOPER - SEČOVLJE,00373,RUDA IZOLA - VALETA,...,SV,BT,O,N,MO,A,393977.0,43662.0,13.637904,45.529127

In [7]:
upravna_enota_df

   id_upravna_enota ime_upravna_enota  st_prebivalcev  povrsina
0              5501        Ajdovščina           23507       353
1              5502           Brežice           23253       268
2              5503             Celje           62049       230
3              5504          Cerknica           16155       483
4              5505          Črnomelj           18290       486
..              ...               ...             ...       ...
59             5564           Maribor          145678       356
60             5565           Pesnica           19750       171
61             5568              Ruše           15054       209
62             5598               MNZ               0         0
63             5599           Neznana               0         0

[64 rows x 4 columns]

In [8]:
# =========================
# RENAME TABLE DATAFRAMES
# =========================

accidents_df = nesreca_df.copy()
persons_df = oseba_df.copy()
administrative_units_df = upravna_enota_df.copy()

# =========================
# RENAME COLUMNS
# =========================

# ---------------------------------
# ACCIDENTS TABLE
# ---------------------------------

accidents_df.rename(columns={

    "id_nesreca": "accident_id",
    "klas_nesreca": "accident_class",
    "upravna_enota": "administrative_unit",
    "cas_nesreca": "accident_time",
    "naselje_ali_izven": "settlement_or_outside",
    "kategorija_cesta": "road_category",
    "oznaka_cesta_ali_naselje": "road_or_settlement_code",
    "tekst_cesta_ali_naselje": "road_or_settlement_name",
    "oznaka_odsek_ali_ulica": "section_or_street_code",
    "tekst_odsek_ali_ulica": "section_or_street_name",
    "stacionazna_ali_hisna_st": "station_or_house_number",
    "opis_prizorisce": "scene_description",
    "vzrok_nesreca": "accident_cause",
    "tip_nesreca": "accident_type",
    "vreme_nesreca": "weather_condition",
    "stanje_promet": "traffic_condition",
    "stanje_vozisce": "road_condition",
    "stanje_povrsina_vozisce": "road_surface_condition",
    "x": "x_coordinate",
    "y": "y_coordinate",
    "x_wgs84": "longitude",
    "y_wgs84": "latitude"

}, inplace=True)

# ---------------------------------
# PERSONS TABLE
# ---------------------------------

persons_df.rename(columns={

    "id_nesreca": "accident_id",
    "povzrocitelj_ali_udelezenec": "causer_or_participant",
    "starost": "age",
    "spol": "gender",
    "upravna_enota": "administrative_unit",
    "drzavljanstvo": "citizenship",
    "poskodba": "injury_type",
    "vrsta_udelezenca": "participant_type",
    "varnostni_pas_ali_celada": "seatbelt_or_helmet",
    "vozniski_staz_LL": "driving_experience_years",
    "vozniski_staz_MM": "driving_experience_months",
    "alkotest": "alcohol_test",
    "strokovni_pregled": "medical_exam",
    "starost_d": "age_group",
    "vozniski_staz_d": "driving_experience_group",
    "alkotest_d": "alcohol_test_group",
    "strokovni_pregled_d": "medical_exam_group"

}, inplace=True)

# ---------------------------------
# ADMINISTRATIVE UNITS TABLE
# ---------------------------------

administrative_units_df.rename(columns={

    "id_upravna_enota": "administrative_unit_id",
    "ime_upravna_enota": "administrative_unit_name",
    "st_prebivalcev": "population",
    "povrsina": "area"

}, inplace=True)

# =========================
# CHECK RENAMED COLUMNS
# =========================

print(accidents_df.columns)
print(persons_df.columns)
print(administrative_units_df.columns)

Index(['accident_id', 'accident_class', 'administrative_unit', 'accident_time',
       'settlement_or_outside', 'road_category', 'road_or_settlement_code',
       'road_or_settlement_name', 'section_or_street_code',
       'section_or_street_name', 'station_or_house_number',
       'scene_description', 'accident_cause', 'accident_type',
       'weather_condition', 'traffic_condition', 'road_condition',
       'road_surface_condition', 'x_coordinate', 'y_coordinate', 'longitude',
       'latitude'],
      dtype='object')
Index(['accident_id', 'causer_or_participant', 'age', 'gender',
       'administrative_unit', 'citizenship', 'injury_type', 'participant_type',
       'seatbelt_or_helmet', 'driving_experience_years',
       'driving_experience_months', 'alcohol_test', 'medical_exam',
       'age_group', 'driving_experience_group', 'alcohol_test_group',
       'medical_exam_group'],
      dtype='object')
Index(['administrative_unit_id', 'administrative_unit_name', 'population',
       'area'],
      dtype='object')

In [25]:
acc_cat=list(set(accidents_df.columns)-set(accidents_df.describe().columns))

In [26]:
acc_cat

['settlement_or_outside',
 'scene_description',
 'accident_cause',
 'accident_type',
 'road_category',
 'traffic_condition',
 'administrative_unit',
 'section_or_street_name',
 'weather_condition',
 'road_condition',
 'road_or_settlement_name',
 'section_or_street_code',
 'station_or_house_number',
 'accident_class',
 'accident_id',
 'road_surface_condition',
 'road_or_settlement_code']

In [30]:
accidents_df[acc_cat].sample(10)

,settlement_or_outside,scene_description,accident_cause,accident_type,road_category,traffic_condition,administrative_unit,section_or_street_name,weather_condition,road_condition,road_or_settlement_name,section_or_street_code,station_or_house_number,accident_class,accident_id,road_surface_condition,road_or_settlement_code
185277,D,P,SV,TV,N,R,5537,MEDNARODNI PREHOD,J,SU,VRTOJBA,00012,None,B,223726,A,37129
54990,N,C,PV,TV,A,R,5524,KOSEZE-BRDO,J,SU,PREDOR KARAVANKE-BREGANA,00014,None,B,093080,A,000A1
479704,D,N,PV,TV,N,N,5524,LITIJSKA CESTA,O,MO,LJUBLJANA,26027,47,U,519990,A,25001
236300,D,N,SV,BT,V,N,5542,NI ULIC,J,SP,CIRKOVCE,00000,3,B,274951,A,42019
7143,D,P,PV,TV,V,N,5506,NI ULIC,J,SU,TROJANE,00000,None,B,045103,A,06129
195332,D,C,VR,NT,N,G,5518,KOROŠKA CESTA,J,MO,KRANJ,00042,None,B,233804,O,18035
147049,D,C,OS,OP,V,R,5516,NI ULIC,J,SU,LIVOLD,00000,None,B,185406,M,16074
321268,N,C,SV,BT,5,R,5550,ŽIČE-POLJČANE,J,SU,SL.KONJICE-ŽIČE-MAJŠPERK,01232,7600,B,360274,A,00688
81173,D,C,HI,NT,M,N,5524,KARL.MOST-ŠKOFLJICA,O,SL,KORENSKO SEDLO - OBREŽJE,00215,0074,B,119369,A,00001
88875,D,P,PV,TV,N,N,5553,PODLUBNIK,J,SU,ŠKOFJA LOKA,00028,None,B,127103,A,53149

In [32]:
# ============================================
# FIND UNIQUE VALUES IN ALL CATEGORICAL COLUMNS
# ============================================

# Select categorical/object columns
categorical_columns = accidents_df.select_dtypes(include=["object"]).columns

# Loop through each categorical column
for column in acc_cat:
    
    print("\n" + "="*60)
    print(f"COLUMN NAME : {column}")
    print("="*60)
    
    # Print unique values
    print(accidents_df[column].unique())
    
    # Print total unique count
    print(f"\nTotal Unique Values : {accidents_df[column].nunique()}")

============================================================
COLUMN NAME : settlement_or_outside
============================================================
['Settlement' 'Outside Settlement']

Total Unique Values : 2

============================================================
COLUMN NAME : scene_description
============================================================
['Curve' 'K' 'R' 'Straight Road' 'Ž' 'Z' 'A' 'M' 'Intersection']

Total Unique Values : 9

============================================================
COLUMN NAME : accident_cause
============================================================
['PR' 'HI' 'SV' 'PD' 'VR' 'PV' 'NP' 'OS' 'CE' 'TO' 'VO']

Total Unique Values : 11

============================================================
COLUMN NAME : accident_type
============================================================
['BT' 'ÈT' 'TO' 'Side Collision' 'NT' 'OP' 'TV' 'PR' 'PP' 'PZ']

Total Unique Values : 10

============================================================
COLUMN NAME : road_category
============================================================
['V' 'L' 'M' 'N' 'R' 'A' None '1' '3' '2' '5' '4' 'T' '0' 'H']

Total Unique Values : 14

============================================================
COLUMN NAME : traffic_condition
============================================================
['R' 'Normal Traffic' 'G' 'E' 'Z']

Total Unique Values : 5

============================================================
COLUMN NAME : administrative_unit
============================================================
['5564' '5511' '5524' '5558' '5517' '5537' '5518' '5565' '5530' '5502'
 '5540' '5514' '5554' '5546' '5560' '5501' '5559' '5510' '5550' '5505'
 '5568' '5523' '5541' '5508' '5536' '5504' '5522' '5538' '5512' '5543'
 '5542' '5521' '5503' '5548' '5562' '5535' '5529' '5516' '5520' '5506'
 '5555' '5509' '5507' '5544' '5552' '5534' '5561' '5556' '5551' '5549'
 '5557' '5519' '5539' '5513' '5553' '5545' '5547' '5515' '5599']

Total Unique Values : 59

============================================================
COLUMN NAME : section_or_street_name
============================================================
['NI ULIC' 'NI ODSEKOV' 'MARIBOR(TEZNO)-HAJDINA' ... 'TARTINIJEVA ULICA'
 'ČEPOVANSKA ULICA' 'PODBREŽNA POT']

Total Unique Values : 6850

============================================================
COLUMN NAME : weather_condition
============================================================
['Cloudy Weather' 'Clear Weather' 'M' 'D' 'S' 'N' 'V' 'T']

Total Unique Values : 8

============================================================
COLUMN NAME : road_condition
============================================================
['Wet Road' 'PN' 'Snowy Road' 'Dry Road' 'Slippery Road' 'SN' 'PP' 'OS'
 'BL']

Total Unique Values : 9

============================================================
COLUMN NAME : road_or_settlement_name
============================================================
['PERNICA' 'IDRIJA-KOČEVŠE-KODER-VOJS' 'MEJA A-VIČ-ORMOŽ-MEJA RH' ...
 'KRKOVO PRI KARLOVICI' 'MEJA' 'SOVINJA PEČ']

Total Unique Values : 8726

============================================================
COLUMN NAME : section_or_street_code
============================================================
['00000' '00246' '01034' ... '28005' '25163' '28031']

Total Unique Values : 3218

============================================================
COLUMN NAME : station_or_house_number
============================================================
[None '0001' '0000' ... '5709' '7081' '12715']

Total Unique Values : 4647

============================================================
COLUMN NAME : accident_class
============================================================
['H' 'Minor Accident' 'L' 'S' 'P' 'Serious Accident']

Total Unique Values : 6

============================================================
COLUMN NAME : accident_id
============================================================
['036738' '036744' '036755' ... '549803' '549804' '549805']

Total Unique Values : 508993

============================================================
COLUMN NAME : road_surface_condition
============================================================
['Asphalt' 'Other Surface' 'Macadam']

Total Unique Values : 3

============================================================
COLUMN NAME : road_or_settlement_code
============================================================
['64043' '93117' '00003' ... '28072' '18044' '15075']

Total Unique Values : 7782

In [31]:
# ============================================
# TRANSLATE / MAP CODE VALUES TO ENGLISH
# ============================================

# --------------------------------------------
# SETTLEMENT OR OUTSIDE
# --------------------------------------------

accidents_df["settlement_or_outside"] = accidents_df["settlement_or_outside"].replace({
    
    "D": "Settlement",
    "N": "Outside Settlement"

})

# --------------------------------------------
# SCENE DESCRIPTION
# --------------------------------------------

accidents_df["scene_description"] = accidents_df["scene_description"].replace({

    "C": "Curve",
    "P": "Straight Road",
    "N": "Intersection"

})

# --------------------------------------------
# ACCIDENT CAUSE
# --------------------------------------------

accidents_df["accident_cause"] = accidents_df["accident_cause"].replace({

    "P": "Speeding",
    "N": "Incorrect Driving Side",
    "C": "Improper Movement",
    "O": "Other Causes"

})

# --------------------------------------------
# ACCIDENT TYPE
# --------------------------------------------

accidents_df["accident_type"] = accidents_df["accident_type"].replace({

    "SV": "Vehicle Collision",
    "PV": "Pedestrian Accident",
    "VR": "Rollover Accident",
    "OS": "Side Collision",
    "HI": "Hit and Run"

})

# --------------------------------------------
# ROAD CATEGORY
# --------------------------------------------

accidents_df["road_category"] = accidents_df["road_category"].replace({

    "TV": "Main Road",
    "BT": "Local Road",
    "NT": "Regional Road",
    "OP": "Highway"

})

# --------------------------------------------
# TRAFFIC CONDITION
# --------------------------------------------

accidents_df["traffic_condition"] = accidents_df["traffic_condition"].replace({

    "N": "Normal Traffic",
    "A": "Heavy Traffic",
    "V": "Dense Traffic",
    "M": "Moderate Traffic",
    "5": "Unknown"

})

# --------------------------------------------
# WEATHER CONDITION
# --------------------------------------------

accidents_df["weather_condition"] = accidents_df["weather_condition"].replace({

    "J": "Clear Weather",
    "O": "Cloudy Weather"

})

# --------------------------------------------
# ROAD CONDITION
# --------------------------------------------

accidents_df["road_condition"] = accidents_df["road_condition"].replace({

    "SU": "Dry Road",
    "MO": "Wet Road",
    "SP": "Snowy Road",
    "SL": "Slippery Road"

})

# --------------------------------------------
# ROAD SURFACE CONDITION
# --------------------------------------------

accidents_df["road_surface_condition"] = accidents_df["road_surface_condition"].replace({

    "A": "Asphalt",
    "M": "Macadam",
    "O": "Other Surface"

})

# --------------------------------------------
# ACCIDENT CLASS
# --------------------------------------------

accidents_df["accident_class"] = accidents_df["accident_class"].replace({

    "B": "Minor Accident",
    "U": "Serious Accident"

})

# ============================================
# CHECK OUTPUT
# ============================================

print(accidents_df.head())

  accident_id  accident_class administrative_unit       accident_time  \
0      036738               H                5564 1995-01-01 15:30:00
1      036744  Minor Accident                5511 1995-01-02 12:45:00
2      036755               L                5564 1995-01-01 06:00:00
3      036756  Minor Accident                5511 1995-01-02 20:10:00
4      036764  Minor Accident                5524 1995-01-03 00:15:00

  settlement_or_outside road_category road_or_settlement_code  \
0            Settlement             V                   64043
1    Outside Settlement             L                   93117
2    Outside Settlement             M                   00003
3            Settlement             M                   010-0
4            Settlement             N                   25001

     road_or_settlement_name section_or_street_code  section_or_street_name  \
0                    PERNICA                  00000                 NI ULIC
1  IDRIJA-KOČEVŠE-KODER-VOJS                  00000              NI ODSEKOV
2   MEJA A-VIČ-ORMOŽ-MEJA RH                  00246  MARIBOR(TEZNO)-HAJDINA
3       MEJA I-ROBIČ - KALCE                  01034       SP.IDRIJA-GODOVIČ
4                  LJUBLJANA                  28067         JADRANSKA ULICA

   ... accident_cause accident_type weather_condition traffic_condition  \
0  ...             PR            BT    Cloudy Weather                 R
1  ...             HI            BT     Clear Weather    Normal Traffic
2  ...             SV            ÈT    Cloudy Weather                 R
3  ...             SV            ÈT     Clear Weather    Normal Traffic
4  ...             PD            ÈT    Cloudy Weather                 R

  road_condition road_surface_condition x_coordinate y_coordinate  longitude  \
0       Wet Road                Asphalt     556102.0     159758.0  15.727149
1       Wet Road                Asphalt     423380.0      95390.0  14.006034
2       Wet Road                Asphalt     555372.0     150260.0  15.716500
3             PN                Asphalt     425085.0      96093.0  14.027932
4     Snowy Road                Asphalt     460758.0     100064.0  14.488174

    latitude
0  46.579510
1  45.998372
2  46.494126
3  46.004886
4  46.043603

[5 rows x 22 columns]

In [33]:
# =====================================================
# COMPLETE TRANSLATION / LABEL MAPPING
# =====================================================

# -----------------------------------------------------
# SCENE DESCRIPTION
# -----------------------------------------------------

accidents_df["scene_description"] = accidents_df["scene_description"].replace({

    "Curve": "Curve",
    "Straight Road": "Straight Road",
    "Intersection": "Intersection",

    "K": "Junction",
    "R": "Roundabout",
    "Ž": "Railway Crossing",
    "Z": "Crosswalk",
    "A": "Highway Area",
    "M": "Bridge / Tunnel"

})

# -----------------------------------------------------
# ACCIDENT CAUSE
# -----------------------------------------------------

accidents_df["accident_cause"] = accidents_df["accident_cause"].replace({

    "PR": "Speeding",
    "HI": "Hit and Run",
    "SV": "Wrong Driving Direction",
    "PD": "Unsafe Distance",
    "VR": "Improper Overtaking",
    "PV": "Pedestrian Violation",
    "NP": "Road Condition Negligence",
    "OS": "Other Causes",
    "CE": "Vehicle Defect",
    "TO": "Technical Failure",
    "VO": "Driver Fatigue"

})

# -----------------------------------------------------
# ACCIDENT TYPE
# -----------------------------------------------------

accidents_df["accident_type"] = accidents_df["accident_type"].replace({

    "BT": "Vehicle Collision",
    "ÈT": "Chain Collision",
    "TO": "Vehicle Overturn",
    "Side Collision": "Side Collision",
    "NT": "Truck Accident",
    "OP": "Obstacle Collision",
    "TV": "Vehicle-Pedestrian Accident",
    "PR": "Road Departure",
    "PP": "Rear-End Collision",
    "PZ": "Parking Accident"

})

# -----------------------------------------------------
# ROAD CATEGORY
# -----------------------------------------------------

accidents_df["road_category"] = accidents_df["road_category"].replace({

    "V": "Urban Road",
    "L": "Local Road",
    "M": "Main Road",
    "N": "National Road",
    "R": "Regional Road",
    "A": "Highway",
    "1": "Category 1 Road",
    "2": "Category 2 Road",
    "3": "Category 3 Road",
    "4": "Category 4 Road",
    "5": "Category 5 Road",
    "T": "Tourist Road",
    "0": "Unknown Road Type",
    "H": "Expressway"

})

# -----------------------------------------------------
# TRAFFIC CONDITION
# -----------------------------------------------------

accidents_df["traffic_condition"] = accidents_df["traffic_condition"].replace({

    "R": "Regular Traffic",
    "Normal Traffic": "Normal Traffic",
    "G": "Heavy Traffic",
    "E": "Light Traffic",
    "Z": "Traffic Congestion"

})

# -----------------------------------------------------
# WEATHER CONDITION
# -----------------------------------------------------

accidents_df["weather_condition"] = accidents_df["weather_condition"].replace({

    "Cloudy Weather": "Cloudy Weather",
    "Clear Weather": "Clear Weather",

    "M": "Foggy Weather",
    "D": "Rainy Weather",
    "S": "Snowy Weather",
    "N": "Night / Dark",
    "V": "Windy Weather",
    "T": "Stormy Weather"

})

# -----------------------------------------------------
# ROAD CONDITION
# -----------------------------------------------------

accidents_df["road_condition"] = accidents_df["road_condition"].replace({

    "Wet Road": "Wet Road",
    "Dry Road": "Dry Road",
    "Snowy Road": "Snowy Road",
    "Slippery Road": "Slippery Road",

    "PN": "Uneven Road",
    "SN": "Snow Covered",
    "PP": "Damaged Surface",
    "OS": "Other Condition",
    "BL": "Mud / Dirt Road"

})

# -----------------------------------------------------
# ACCIDENT CLASS
# -----------------------------------------------------

accidents_df["accident_class"] = accidents_df["accident_class"].replace({

    "H": "Fatal Accident",
    "Minor Accident": "Minor Accident",
    "L": "Accident with Injuries",
    "S": "Severe Accident",
    "P": "Property Damage Only",
    "Serious Accident": "Serious Accident"

})

# =====================================================
# CHECK CLEANED DATA
# =====================================================

print(accidents_df.head())

  accident_id          accident_class administrative_unit       accident_time  \
0      036738          Fatal Accident                5564 1995-01-01 15:30:00
1      036744          Minor Accident                5511 1995-01-02 12:45:00
2      036755  Accident with Injuries                5564 1995-01-01 06:00:00
3      036756          Minor Accident                5511 1995-01-02 20:10:00
4      036764          Minor Accident                5524 1995-01-03 00:15:00

  settlement_or_outside  road_category road_or_settlement_code  \
0            Settlement     Urban Road                   64043
1    Outside Settlement     Local Road                   93117
2    Outside Settlement      Main Road                   00003
3            Settlement      Main Road                   010-0
4            Settlement  National Road                   25001

     road_or_settlement_name section_or_street_code  section_or_street_name  \
0                    PERNICA                  00000                 NI ULIC
1  IDRIJA-KOČEVŠE-KODER-VOJS                  00000              NI ODSEKOV
2   MEJA A-VIČ-ORMOŽ-MEJA RH                  00246  MARIBOR(TEZNO)-HAJDINA
3       MEJA I-ROBIČ - KALCE                  01034       SP.IDRIJA-GODOVIČ
4                  LJUBLJANA                  28067         JADRANSKA ULICA

   ...           accident_cause      accident_type weather_condition  \
0  ...                 Speeding  Vehicle Collision    Cloudy Weather
1  ...              Hit and Run  Vehicle Collision     Clear Weather
2  ...  Wrong Driving Direction    Chain Collision    Cloudy Weather
3  ...  Wrong Driving Direction    Chain Collision     Clear Weather
4  ...          Unsafe Distance    Chain Collision    Cloudy Weather

  traffic_condition road_condition road_surface_condition x_coordinate  \
0   Regular Traffic       Wet Road                Asphalt     556102.0
1    Normal Traffic       Wet Road                Asphalt     423380.0
2   Regular Traffic       Wet Road                Asphalt     555372.0
3    Normal Traffic    Uneven Road                Asphalt     425085.0
4   Regular Traffic     Snowy Road                Asphalt     460758.0

  y_coordinate  longitude   latitude
0     159758.0  15.727149  46.579510
1      95390.0  14.006034  45.998372
2     150260.0  15.716500  46.494126
3      96093.0  14.027932  46.004886
4     100064.0  14.488174  46.043603

[5 rows x 22 columns]

In [22]:
accidents_df.describe()

,accident_time,x_coordinate,y_coordinate,longitude,latitude
count,508993,416090.000000,416090.000000,416090.000000,416090.000000
mean,2001-05-14 08:01:18.530352896,496499.143255,116093.396844,14.952511,46.186825
min,1995-01-01 00:30:00,378087.000000,32190.000000,13.414002,45.429954
25%,1998-03-31 14:45:00,460238.000000,99549.000000,14.481125,46.039019
50%,2001-06-30 22:00:00,498925.000000,116895.000000,14.981246,46.194960
75%,2004-08-06 06:00:00,547478.000000,142081.000000,15.613260,46.419447
max,2006-12-31 23:00:00,617552.000000,192709.000000,16.527325,46.871338
std,NaN,53881.935166,32851.739216,0.697772,0.295807

In [10]:
persons_df.describe()

,age,driving_experience_years,driving_experience_months,alcohol_test,medical_exam
count,952702.000000,799528.000000,706826.000000,544056.000000,546240.000000
mean,36.016177,13.077905,3.296370,0.115467,0.035315
std,14.597524,10.917235,3.707125,0.428967,0.250034
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,24.000000,4.000000,0.000000,0.000000,0.000000
50%,33.000000,10.000000,2.000000,0.000000,0.000000
75%,45.000000,20.000000,6.000000,0.000000,0.000000
max,99.000000,99.000000,11.000000,9.830000,9.100000

In [11]:
administrative_units_df.describe()

          population        area
count      64.000000   64.000000
mean    51634.484375  371.312500
std     83565.303993  248.104233
min         0.000000    0.000000
25%     17000.000000  206.000000
50%     21207.000000  319.000000
75%     40161.000000  487.750000
max    326525.000000  939.000000

In [35]:
categorical_cols = persons_df.select_dtypes(include=['object', 'category']).columns
print("Categorical Columns:", list(categorical_cols))

Categorical Columns: ['accident_id', 'causer_or_participant', 'gender', 'administrative_unit', 'citizenship', 'injury_type', 'participant_type', 'seatbelt_or_helmet', 'age_group', 'driving_experience_group', 'alcohol_test_group', 'medical_exam_group']

In [37]:
unique_values = {}

for col in categorical_cols:
    unique_values[col] = persons_df[col].dropna().unique().tolist()

    print("\n" + "="*70)
    print("COLUMN:", col)
    print("="*70)
    print(unique_values[col])
    print("\nTotal Unique Values:", len(unique_values[col]))

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

======================================================================
COLUMN: administrative_unit
======================================================================
['5507', '5599', '5511', '5524', '5542', '5528', '5558', '5527', '5525', '5537', '5506', '5550', '5564', '5518', '5502', '5540', '5514', '5554', '5546', '5517', '5560', '5501', '5548', '5559', '5510', '5541', '5551', '5544', '5553', '5509', '5561', '5523', '5526', '5508', '5503', '5556', '5504', '5538', '5522', '5530', '5536', '5565', '5545', '5552', '5515', '5549', '5562', '5543', '5512', '5535', '5521', '5555', '5529', '5513', '5557', '5520', '5568', '5534', '5519', '5516', '5539', '5505', '5547']

Total Unique Values: 63

======================================================================
COLUMN: citizenship
======================================================================
['005', '211', '120', '003', '001', '202', '223', '010', '104', '999', '112', '100', '221', '204', '208', '215', '130', '004', '131', '350', '106', '206', '502', '107', '116', '102', '122', '628', '219', '336', '203', '434', '119', '114', '101', '113', '220', '329', '361', '312', '501', '500', '401', '700', '319', '447', '325', '620', '111', '213', '309', '351', '323', '117', '424', '205', '000', '207', '212', '407', '438', '311', '322', '428', '225', '344', '315', '624', '216', '333', '115', '210', '416', '408', '314', '313', '217', '123', '321', '209', '623', '121', '347', '310', '306', '411', '305', '414', '308', '006', '630', '417', '433', '218', '608', '332', '605', '505', '442', '626', '413', '622', '326', '998', '607', '320', '334', '601', '405', '432', '301', '330', '437', '224', '002', '363']

Total Unique Values: 116

======================================================================
COLUMN: injury_type
======================================================================
['L', 'P', 'H', 'B', 'S', 'U']

Total Unique Values: 6

======================================================================
COLUMN: participant_type
======================================================================
['TV', 'OA', 'PT', 'AV', 'PE', 'OS', 'KO', 'SV', 'DS', 'MK', 'TR', 'OD', 'KM', 'KV', 'MO', 'PO', 'SM', 'KR', 'LK', 'TK', 'SK', 'SP', 'SD']

Total Unique Values: 23

======================================================================
COLUMN: seatbelt_or_helmet
======================================================================
['N', '0', 'D', '1', '2', '*']

Total Unique Values: 6

======================================================================
COLUMN: age_group
======================================================================
['D', 'C', 'B', 'E', 'F', 'G', 'A', 'I', 'H', 'J', 'N']

Total Unique Values: 11

======================================================================
COLUMN: driving_experience_group
======================================================================
['B', 'A', 'D', 'E', 'C', 'N', 'F', 'G', 'J', 'H', 'I']

Total Unique Values: 11

======================================================================
COLUMN: alcohol_test_group
======================================================================
['B', 'A', 'N', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

Total Unique Values: 11

======================================================================
COLUMN: medical_exam_group
======================================================================
['B', 'A', 'N', 'E', 'F', 'D', 'C', 'G', 'H', 'I', 'J']

Total Unique Values: 11