In [1]:
import pandas as pd

In [4]:
df=pd.DataFrame({'Name':['Parth','Priyanshu','Rishabh','Arman','Suraj',"Aman"],
                'Age':[21,22,23,24,23,21],
                'City':['Bhopal','Raisen','Indore','Gwalior','Jabalpur','Raisen']},index=['a','b','c','d','e','f'])
df

        Name  Age      City
a      Parth   21    Bhopal
b  Priyanshu   22    Raisen
c    Rishabh   23    Indore
d      Arman   24   Gwalior
e      Suraj   23  Jabalpur
f       Aman   21    Raisen

In [6]:
# loc - label based indexing
# loc[rows,columns]
df.loc[['a','b','d']]

        Name  Age     City
a      Parth   21   Bhopal
b  Priyanshu   22   Raisen
d      Arman   24  Gwalior

In [7]:
df.loc[['a','b','d'],['Name']]

        Name
a      Parth
b  Priyanshu
d      Arman

In [9]:
df.loc[::,['Name',"City"]]

        Name      City
a      Parth    Bhopal
b  Priyanshu    Raisen
c    Rishabh    Indore
d      Arman   Gwalior
e      Suraj  Jabalpur
f       Aman    Raisen

In [12]:
df.loc[df['City']=='Raisen']

        Name  Age    City
b  Priyanshu   22  Raisen
f       Aman   21  Raisen

In [13]:
df.loc[:'d':,:'Age':]

        Name  Age
a      Parth   21
b  Priyanshu   22
c    Rishabh   23
d      Arman   24

In [14]:
df.iloc[0::2,[0,-1]]

      Name      City
a    Parth    Bhopal
c  Rishabh    Indore
e    Suraj  Jabalpur

In [15]:
df.iloc[:4:,::]

        Name  Age     City
a      Parth   21   Bhopal
b  Priyanshu   22   Raisen
c    Rishabh   23   Indore
d      Arman   24  Gwalior

In [16]:
df.loc[:"e":,::]

        Name  Age      City
a      Parth   21    Bhopal
b  Priyanshu   22    Raisen
c    Rishabh   23    Indore
d      Arman   24   Gwalior
e      Suraj   23  Jabalpur

In [17]:
df=pd.DataFrame({'Name':['Parth','Priyanshu','Rishabh','Arman','Suraj',"Aman"],
                'Age':[21,22,23,24,23,21],
                'City':['Bhopal','Raisen','Indore','Gwalior','Jabalpur','Raisen']})
df

        Name  Age      City
0      Parth   21    Bhopal
1  Priyanshu   22    Raisen
2    Rishabh   23    Indore
3      Arman   24   Gwalior
4      Suraj   23  Jabalpur
5       Aman   21    Raisen

In [18]:
df.iloc[:4:,::]

        Name  Age     City
0      Parth   21   Bhopal
1  Priyanshu   22   Raisen
2    Rishabh   23   Indore
3      Arman   24  Gwalior

In [19]:
df.loc[:4:,::]

        Name  Age      City
0      Parth   21    Bhopal
1  Priyanshu   22    Raisen
2    Rishabh   23    Indore
3      Arman   24   Gwalior
4      Suraj   23  Jabalpur