In [12]:


                import pandas as pd

In [13]:
df1=pd.DataFrame({"A":[1,2,3,4,5],"B":[10,20,30,40,50]})
df1

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [14]:
df2=pd.DataFrame({"A":[1,2,3,4,6],"B":[1000,2000,3000,4000,5000]})
df2

   A     B
0  1  1000
1  2  2000
2  3  3000
3  4  4000
4  6  5000

In [15]:
df=pd.merge(df1,df2,how="cross")
df

    A_x  B_x  A_y   B_y
0     1   10    1  1000
1     1   10    2  2000
2     1   10    3  3000
3     1   10    4  4000
4     1   10    6  5000
5     2   20    1  1000
6     2   20    2  2000
7     2   20    3  3000
8     2   20    4  4000
9     2   20    6  5000
10    3   30    1  1000
11    3   30    2  2000
12    3   30    3  3000
13    3   30    4  4000
14    3   30    6  5000
15    4   40    1  1000
16    4   40    2  2000
17    4   40    3  3000
18    4   40    4  4000
19    4   40    6  5000
20    5   50    1  1000
21    5   50    2  2000
22    5   50    3  3000
23    5   50    4  4000
24    5   50    6  5000

In [16]:
df=pd.merge(df1,df2,on="A",how="inner")
df

   A  B_x   B_y
0  1   10  1000
1  2   20  2000
2  3   30  3000
3  4   40  4000

In [17]:
df=pd.merge(df1,df2,on="A",how="right")
df

   A   B_x   B_y
0  1  10.0  1000
1  2  20.0  2000
2  3  30.0  3000
3  4  40.0  4000
4  6   NaN  5000

In [18]:
df=pd.merge(df1,df2,on="A",how="outer")
df

   A   B_x     B_y
0  1  10.0  1000.0
1  2  20.0  2000.0
2  3  30.0  3000.0
3  4  40.0  4000.0
4  5  50.0     NaN
5  6   NaN  5000.0

In [19]:
df=pd.merge(df1,df2,on="A",how="inner")
df

   A  B_x   B_y
0  1   10  1000
1  2   20  2000
2  3   30  3000
3  4   40  4000

In [20]:
df1=pd.DataFrame({"A":[1,2,3,4,5],"B":[10,20,30,40,50]})
df1

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [21]:
df2=pd.DataFrame({"C":[1,2,3,4,6],"D":[1000,2000,3000,4000,5000]})
df2

   C     D
0  1  1000
1  2  2000
2  3  3000
3  4  4000
4  6  5000

In [24]:
df=pd.merge(df1,df2,left_on="A",right_on="C",how="inner")
df

   A   B  C     D
0  1  10  1  1000
1  2  20  2  2000
2  3  30  3  3000
3  4  40  4  4000

In [25]:
df=pd.merge(df1,df2,left_on="A",right_on="C",how="left")
df

   A   B    C       D
0  1  10  1.0  1000.0
1  2  20  2.0  2000.0
2  3  30  3.0  3000.0
3  4  40  4.0  4000.0
4  5  50  NaN     NaN

In [26]:
df=pd.merge(df1,df2,left_on="A",right_on="C",how="left")
df

   A   B    C       D
0  1  10  1.0  1000.0
1  2  20  2.0  2000.0
2  3  30  3.0  3000.0
3  4  40  4.0  4000.0
4  5  50  NaN     NaN

In [27]:
df=pd.merge(df1,df2,left_on="A",right_on="C",how="outer")
df

     A     B    C       D
0  1.0  10.0  1.0  1000.0
1  2.0  20.0  2.0  2000.0
2  3.0  30.0  3.0  3000.0
3  4.0  40.0  4.0  4000.0
4  5.0  50.0  NaN     NaN
5  NaN   NaN  6.0  5000.0